# Generated by Django 4.0.3 on 2022-05-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0002_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='Tenses',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='English',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='French',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='Tenses',
            field=models.CharField(max_length=500),
        ),
    ]
